### ISSUE TITLE
I don't know what this means

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/saas-website#2]
@muxlowc @HannahDelaney
I'm not quite sure on how to fix these. My tour.html seems to be perfectly fine, however, I don't know where exactly to fix the issue

<img width="517" alt="Screen Shot 2020-04-20 at 2 32 35 PM" src="https://user-images.githubusercontent.com/54897840/79786895-1d288200-8314-11ea-946f-bffbf1c939c4.png">

**Comment by HannahDelaney** [comment]
This error usually means that one of these sections is missing, or it is present but doesn't have an `<a>` tag link anywhere. On the index.html or sign-up.html pages, you need to have links in those areas of the page. Since websites are meant to link you to places where you can continue viewing content, or in this case, sign up or pay money, if there are no links then the site can't achieve it's base function. That's why this error appears.

You might have `<a>` tags somewhere, but not in the main, or section, or article.

**Comment by Sophia-Villamayor** [comment]
@HannahDelaney 
Thank you!!
